name: release-buildx

on: [push, pull_request]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Create tag for Docker image
        uses: Surgo/docker-smart-tag-action@v1
        id: smarttag
        with:
          docker_image: tsuru/rate-limit-control-plane
          default_branch: master
          tag_with_sha: "true"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        if: github.event_name != 'pull_request'
        with:
          push: true
          tags: ${{ steps.smarttag.outputs.tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          platforms: linux/amd64
